spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:27544/railway
spring.datasource.username=root
spring.datasource.password=FLwTLvqQRQNPcKkevtzOKlTYVJyWFjPT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
